### ISSUE TITLE
Build multi-platform wheels when changes are finalized

### ISSUE THREAD

**Issue by RDmitchell** [LBNL-ETA/pyWinCalc#18]
@StephenCzarnecki -- I believe Taoning volunteered to build the multi-platform wheels when you are finished with your current set of changes.

**Comment by RDmitchell** [comment]
@taoning -- if you still have time to do this, coordinate with @StephenCzarnecki because I think the code is to the point where we can build the multi-platform wheels. 

And if you don't have time to do it, just let us know. 

Thanks !

**Comment by taoning** [comment]
Sounds good. I will coordinate with @StephenCzarnecki

**Comment by RDmitchell** [comment]
Thanks !

**Comment by taoning** [comment]
We have now multi-platform builds. https://github.com/LBNL-ETA/pyWinCalc/actions/runs/1867005422
