### ISSUE TITLE
Automate building multi-platform wheels

### ISSUE THREAD

**Issue by RDmitchell** [LBNL-ETA/pyWinCalc#19]
Again, I believe Taoning volunteered to help set this up, as I believe he is doing at least semi-automated wheel building for Radiance.

**Comment by RDmitchell** [comment]
@taoning -- I have added you to this repo

This issue is priority 2 so no rush, just when you can get to it, if you still think you have time to help @StephenCzarnecki set this up. Thx

**Comment by taoning** [comment]
Wheel building is now automated with every commit or pull requests to the main branch.
