### ISSUE TITLE
Values not matching in WINDOW

### ISSUE THREAD

**Issue by joshtate** [LBNL-ETA/pyWinCalc#2]
I'm having an issue on certain glazing systems where it does not match the values in WINDOW.  Here are the versions I'm using:

- IGDB v66.0
- WINDOW 7.7
- Optics 6.0 (Maintenance Pack 1)

For both examples, width and height are set to 1.0m with standard `W5_NFRC_2003.std` 

Also, [here are the exported Optics files](https://github.com/LBNL-ETA/pyWinCalc/files/3311718/products.zip) that were used in the script, but for someone testing this you may want to export them yourself to see if there is any discrepancy there.

### Glazing System 1 (closely matches WINDOW):
Glass 1: Activ6.lof
Gap 1: AIR @ .0127m
Glass 2: Clear_6.VTA

|         | pyWinCalc | WINDOW | _Difference_ |
|:-------:|---------|--------|--------|
| U-Value | 2.690   | 2.689  | _0.001_ |
| SHGC    | 0.679   | 0.679  | - |
| Tvis    | 0.740   | 0.740  | - | 
| Tsol    | 0.5873   | 0.5873  | - |
| Tuv    | 0.3483   | 0.3475  | _0.0008_ |

### Glazing System 2 (not matching WINDOW):
Glass 1: SB60 Clear_6.VTA
Gap 1: AIR @ .0127m
Glass 2: Clear_6.VTA

|         | pyWinCalc | WINDOW | _Difference_ |
|:-------:|---------|--------|--------|
| U-Value | 2.690   | 1.651  | _1.039_ |
| SHGC    | 0.412   | 0.391  | _0.021_ |
| Tvis    | 0.704   | 0.704  | - |
| Tsol    | 0.3356   | 0.3355  | _0.0001_ |
| Tuv    | 0.1736   | 0.1812  | _(0.0076)_ |

Could anyone explain why these values are not matching?

**Comment by StephenCzarnecki** [comment]
Hi

The values should match WINDOW.  We found a couple calculation bugs that we’ve been fixing and are currently testing the fixes.  Thanks for the comparison and sending the files that you were using, I’ll add your system those to the ones we are testing.  

I’ll let you know if the current round of bug fixes resolve the differences in results you are seeing.  If they do not then we’ll try to find whatever is causing the differences.

**Comment by StephenCzarnecki** [comment]
Thanks for submitting this issue, it was indeed another bug.  I think I've patched it in the latest code.  TUV should also be much closer to WINDOW now.

I should say I'm doing the unwise thing of making a patch immediately before going on vacation.  The values you were seeing were bad enough that I wanted to correct the issue sooner rather than later.  

If you find any more inconsistencies with WINDOW or have any other problems please let us know.  Hopefully someone else may be able to help you before I am back.  Otherwise I will be back on July 1st.

**Comment by joshtate** [comment]
Glad to hear you were able to reproduce my issue!  I'll give this a try later today or early next week and I'll report back with my findings.

**Comment by StephenCzarnecki** [comment]
Ok thanks.  As I mentioned before I'll be away today and next week with not
much internet access.  So apologies in advance if something goes wrong.
I'll be back July 1st.

**Comment by joshtate** [comment]
The new version is producing consistent results now.  Thank you!
