### ISSUE TITLE
(More a Question, than an Issue) genBSDF shades in glazing systems. 

### ISSUE THREAD

**Issue by Rasmus1422** [LBNL-ETA/pyWinCalc#41]
Hi All

I have created a series of BSDF Shades through genBSDF. However, when creating the glazing system, I get an error that only LBNL/Klems Full is supported. However, the files are created as Full Klems but only with the wavelength in the Visible. The files work perfectly in Window 7. Can I get a further explanation of the error? 

Great work with implementation! 

Best Rasmus

**Comment by Rasmus1422** [comment]
Hi 

Thanks for taking the time, was unsure where to post my question. 

`import pywincalc

gas = pywincalc.create_gas([[0.1, pywincalc.PredefinedGasType.AIR], [0.9, pywincalc.PredefinedGasType.ARGON]])

gap_1 = pywincalc.Layers.gap(thickness=0.014, gas=gas)
gap_2 = pywincalc.Layers.gap(thickness=0.0001, gas=gas)
gap_3 = pywincalc.Layers.gap(thickness=0.014, gas=gas)

gaps = [gap_2, gap_1]

clear_3_path = "Path/CLEAR_3.DAT"

bsdf_path = "Path/microshade_MS3_F_20200701_3.xml"

clear_3 = pywincalc.parse_optics_file(clear_3_path)
bsdf_shade = pywincalc.parse_bsdf_xml_file(bsdf_path)

solid_layers = [clear_3,bsdf_shade,clear_3]

bsdf_hemisphere = pywincalc.BSDFHemisphere.create(pywincalc.BSDFBasisType.FULL)

front_transmittance_matrix = pywincalc.SquareMatrix(bsdf_shade.measurements.solar.transmittance_front.data)

glazing_system = pywincalc.GlazingSystem(solid_layers=solid_layers,gap_layers=gaps)

u_value = glazing_system.u()
print("U-value for a BSDF shade created from a local file: {v}".format(v=u_value))`

I have taken the code from the example case posted in your repository. The Glazings used is the CLEAR_3 posted in your repository. My BSDF XML file is created through genBSDF and describes a complex fenestration system (I have attached the file). The BSDF is created with only the Visible Wavelength for Transmission Front/Back. 

Thanks for the help and the great work on the package. 

[GlazingSystemFiles.zip](https://github.com/LBNL-ETA/pyWinCalc/files/11660892/GlazingSystemFiles.zip)

**Comment by vidanovic** [comment]
You must create solar range as well for now. This is an example file. 

[2011-SA1.zip](https://github.com/LBNL-ETA/pyWinCalc/files/11696877/2011-SA1.zip)

If you want to keep the same data over the solar range then you can just copy your visible into solar. But you need to have 8 sections as in the file.

**Comment by Rasmus1422** [comment]
Thanks, I will do that, and again great work with the package.

**Comment by RDmitchell** [comment]
Closed as the user was instructed how to do this calculation
